# Generated by Django 5.1.3 on 2026-01-29 15:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unique_id', models.CharField(max_length=36, unique=True)),
                ('title', models.CharField(max_length=500)),
                ('author_name', models.CharField(blank=True, max_length=255, null=True)),
                ('description_html', models.TextField(blank=True, null=True)),
                ('publication_date', models.DateTimeField(blank=True, null=True)),
                ('image_url', models.URLField(blank=True, max_length=1000, null=True)),
                ('total_borrowed', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'indexes': [models.Index(fields=['title'], name='crazyLibApp_title_4fefa6_idx'), models.Index(fields=['author_name'], name='crazyLibApp_author__dfe7a9_idx'), models.Index(fields=['total_borrowed'], name='crazyLibApp_total_b_3db1ed_idx')],
            },
        ),
        migrations.CreateModel(
            name='BookCopy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('call_number', models.CharField(max_length=200, unique=True)),
                ('available', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='copies', to='crazyLibApp.book')),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('phone', models.CharField(blank=True, max_length=50, null=True)),
                ('passport', models.CharField(max_length=50, unique=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('birth_date', models.DateTimeField(blank=True, null=True)),
                ('address', models.CharField(blank=True, max_length=255, null=True)),
                ('city_raw', models.CharField(blank=True, max_length=255, null=True)),
                ('zip', models.CharField(blank=True, max_length=20, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'indexes': [models.Index(fields=['last_name', 'first_name'], name='crazyLibApp_last_na_4c4cbb_idx'), models.Index(fields=['phone'], name='crazyLibApp_phone_d75ede_idx')],
            },
        ),
        migrations.CreateModel(
            name='LibraryEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('BORROW', 'Borrow'), ('RELEASE', 'Release')], max_length=10)),
                ('action_dt', models.DateTimeField()),
                ('source_hash', models.CharField(blank=True, max_length=64, null=True, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('book_copy', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='events', to='crazyLibApp.bookcopy')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='events', to='crazyLibApp.customer')),
            ],
        ),
        migrations.AddIndex(
            model_name='bookcopy',
            index=models.Index(fields=['book'], name='crazyLibApp_book_id_510588_idx'),
        ),
        migrations.AddIndex(
            model_name='bookcopy',
            index=models.Index(fields=['available'], name='crazyLibApp_availab_f19483_idx'),
        ),
        migrations.AddIndex(
            model_name='libraryevent',
            index=models.Index(fields=['customer', 'action_dt'], name='crazyLibApp_custome_9466db_idx'),
        ),
        migrations.AddIndex(
            model_name='libraryevent',
            index=models.Index(fields=['book_copy', 'action_dt'], name='crazyLibApp_book_co_1f3c19_idx'),
        ),
        migrations.AddIndex(
            model_name='libraryevent',
            index=models.Index(fields=['event_type', 'action_dt'], name='crazyLibApp_event_t_fe6480_idx'),
        ),
    ]
